version: '2'
services:
  eurekaserver:
    image: bhhan87/eurekaserver:v1.0
    ports:
      - "8761:8761"
  configserver:
    image: bhhan87/config-server:v1.0
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY: "IMSYMMETRIC"
  zuulserver:
    image: bhhan87/zuul-gateway:v1.0
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URL: "http://configserver:8888"
      CONFIGSERVER_PORT: "8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka"
      EUREKASERVER_PORT: "8761"
      DATABASESERVER_PORT: "5432"
      ORGSERVERNEW_PORT: "8087"
      JWT_KEY: "bhhan"
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_DB: "eagle_eye_local"
  licensingservice:
    image: bhhan87/licensing-service:v1.0
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URL: "http://configserver:8888"
      CONFIGSERVER_PORT: "8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka"
      EUREKASERVER_PORT: "8761"
      AUTHSERVER_PORT: "8091"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
      SERVER_PORT: "8080"
      AUTHSERVER_URI: "http://authenticationservice:8901/auth/user"
      ORGSERVERNEW_PORT: "8087"
      ZUULSERVER_PORT: "5555"
      JWT_KEY: "bhhan"
  organizationservice:
    image: bhhan87/organization-service:v1.0
    ports:
      - "8085:8085"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URL: "http://configserver:8888"
      CONFIGSERVER_PORT: "8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka"
      EUREKASERVER_PORT: "8761"
      DATABASESERVER_PORT: "5432"
      SERVER_PORT: "8085"
      ENCRYPT_KEY: "IMSYMMETRIC"
      AUTHSERVER_URI: "http://authenticationservice:8901/auth/user"
      JWT_KEY: "bhhan"
  orgservice-new:
    image: bhhan87/organization-new:v1.0
    ports:
      - "8087:8087"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URL: "http://configserver:8888"
      CONFIGSERVER_PORT: "8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka"
      EUREKASERVER_PORT: "8761"
      DATABASESERVER_PORT: "5432"
      SERVER_PORT: "8087"
      ENCRYPT_KEY: "IMSYMMETRIC"
  specialroutes-service:
    image: bhhan87/specialroutes-service:v1.0
    ports:
      - "8910:8910"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8910"
      CONFIGSERVER_URL: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  authenticationservice:
    image: bhhan87/authentication-service:v1.0
    ports:
      - "8901:8901"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8901"
      DATABASE_PORT: "5432"
      CONFIGSERVER_PORT: "8888"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      ENCRYPT_KEY: "IMSYMMETRIC"
      JWT_KEY: "bhhan"